spring.application.name=employee-batch-processor

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/employeedb
spring.datasource.username=batchuser
spring.datasource.password=batchpass
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false